import { Builder } from './builder';

/**
 * Entity is an object generated by runtime. It could be a DOM element, block,
 * iterator etc. Every object must be created and optionally updated and destroyed.
 */
export default class Entity {
    constructor(public name: string, public create?: Builder, public update?: Builder, public destroy?: Builder) {

    }
}

// export function functionBuilder(state: CompileState, fnName: string, injector?: boolean): Builder {

// }
